# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maishuapply.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys

sys.path.append("../")  # 返回上层路径
from service import service, myservice


class Ui_MainWindow(QMainWindow):
    # 构造方法
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)  # 只显示最小化和关闭按钮
        self.setupUi(self)  # 初始化窗体设置
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(334, 249)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.bindclass()
        self.pushButton.clicked.connect(self.add)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def bindclass(self):
        '''
        修改下拉栏
        '''
        # self.cboxclass.addItem("所有")
        result = myservice.query2("select distinct Bclass from tb_book")
        for i in result:  # 遍历查询结果
            self.comboBox.addItem(i[0])  # 在下拉列表中显示
    def add(self):
        name = self.lineEdit.text()
        price = self.lineEdit_2.text()
        author = self.lineEdit_3.text()
        bclass = self.comboBox.currentText()
        num=myservice.query2("select count(*) from tb_book where Bname='{}'".format(name))[0][0]
        if num!=0:
            result = myservice.exec("update tb_book set Bnum=Bnum+1 where Bname='{}'".format(name))
        else:
            result = myservice.exec("insert into tb_book(Bname,Bprice,Bauthor,Bclass,Bnum) value('{}','{}','{}','{}',1)".format(name,price,author,bclass))
        QMessageBox.information(None, '提示', 'OK！', QMessageBox.Ok)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "卖书申请"))
        self.label.setText(_translate("MainWindow", "书名"))
        self.label_2.setText(_translate("MainWindow", "价格"))
        self.label_5.setText(_translate("MainWindow", "类型"))
        self.pushButton.setText(_translate("MainWindow", "申请"))
        self.label_4.setText(_translate("MainWindow", "作者"))
# 主方法
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
    ui = Ui_MainWindow() # 创建PyQt5设计的窗体对象
    ui.setupUi(MainWindow) # 调用PyQt5窗体的方法对窗体对象进行初始化设置
    MainWindow.show() # 显示窗体
    sys.exit(app.exec_()) # 程序关闭时退出进程
    # name='龙族'
    # num = myservice.query2("select count(*) from tb_book where Bname='{}'".format(name))[0][0]
    # print(num)
