# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weihu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys

sys.path.append("../")  # 返回上层路径
from service import service, myservice


class Ui_MainWindow(QMainWindow):
    # 构造方法
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)  # 只显示最小化和关闭按钮
        self.setupUi(self)  # 初始化窗体设置
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 421)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setObjectName("btnEdit")
        self.gridLayout.addWidget(self.btnEdit, 3, 1, 1, 1)
        self.tbUser = QtWidgets.QTableWidget(self.centralwidget)
        self.tbUser.setObjectName("tbUser")
        self.tbUser.setColumnCount(2)
        self.tbUser.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbUser.setHorizontalHeaderItem(1, item)
        # self.tbUser.horizontalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.tbUser, 0, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 3, 0, 1, 1)
        self.btnDel = QtWidgets.QPushButton(self.centralwidget)
        self.btnDel.setObjectName("btnDel")
        self.gridLayout.addWidget(self.btnDel, 3, 2, 1, 1)
        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setObjectName("editName")
        self.gridLayout.addWidget(self.editName, 1, 1, 1, 2)
        self.editPwd = QtWidgets.QLineEdit(self.centralwidget)
        self.editPwd.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.editPwd.setObjectName("editPwd")
        self.gridLayout.addWidget(self.editPwd, 2, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.reflash()
        self.btnAdd.clicked.connect(self.add)
        self.btnEdit.clicked.connect(self.chongzhi)
        self.btnDel.clicked.connect(self.deluser)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "用户信息维护"))
        self.label_3.setText(_translate("MainWindow", "用户名："))
        self.btnEdit.setText(_translate("MainWindow", "密码重置"))
        item = self.tbUser.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "用户名"))
        item = self.tbUser.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "账号类型"))
        self.label_2.setText(_translate("MainWindow", "姓名："))
        self.btnAdd.setText(_translate("MainWindow", "添加"))
        self.btnDel.setText(_translate("MainWindow", "删除"))

    def reflash(self):
        '''
        刷新表格内容
        '''
        self.tbUser.setRowCount(0)  # 清空表格中的所有行
        result = myservice.query2("select Uname,Uuser,Uclass from tb_user")  # 调用服务类中的公共方法执行查询语句
        row = len(result)  # 取得记录个数，用于设置表格的行数
        self.tbUser.setRowCount(row)  # 设置表格行数
        self.tbUser.setColumnCount(3)  # 设置表格列数
        # 设置表格的标题名称
        self.tbUser.setHorizontalHeaderLabels(['姓名','用户名', '账号类型'])
        for i in range(row):  # 遍历行
            for j in range(self.tbUser.columnCount()):  # 遍历列
                data = QTableWidgetItem(str(result[i][j]))  # 转换后可插入表格
                self.tbUser.setItem(i, j, data)  # 设置每个单元格的数据
    def add(self):
        t1=self.editName.text()
        t2=self.editPwd.text()
        # print(t1,t2)
        result = myservice.exec("insert into tb_user(Uname,Uuser,Uclass) values('{}','{}','普通');".format(t1,t2))
        self.reflash()
        # print(result)
    def chongzhi(self):
        t2 = self.editPwd.text()
        chongzhiresult = myservice.exec("update tb_pwd set password='111111' where user={}".format(t2))
        QMessageBox.information(None, '提示', '密码修改为初始密码：111111\n请尽快修改!', QMessageBox.Ok)
    def deluser(self):
        t2 = self.editPwd.text()
        delresult=myservice.exec("delete from tb_user where Uuser= {};".format(t2))
        self.reflash()


# 主方法
if __name__ == '__main__':

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
    ui = Ui_MainWindow() # 创建PyQt5设计的窗体对象
    ui.setupUi(MainWindow) # 调用PyQt5窗体的方法对窗体对象进行初始化设置
    MainWindow.show() # 显示窗体
    sys.exit(app.exec_()) # 程序关闭时退出进程

    # result = myservice.exec(
    #     "insert into tb_user(Uname,Uuser,Upassword,Uclass) values({},{},{},'普通'".format('算法', 124, 111111))
    # print(result)
