# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rengongzhineng.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys  # 导入sys模块
import yichuan

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.population_size = QtWidgets.QLabel(self.centralwidget)
        self.population_size.setObjectName("population_size")
        self.gridLayout.addWidget(self.population_size, 0, 0, 1, 2)
        self.popu_size = QtWidgets.QLineEdit(self.centralwidget)
        self.popu_size.setObjectName("popu_size")
        self.gridLayout.addWidget(self.popu_size, 0, 2, 1, 2)
        self.generations = QtWidgets.QLabel(self.centralwidget)
        self.generations.setObjectName("generations")
        self.gridLayout.addWidget(self.generations, 1, 0, 1, 2)
        self.gene = QtWidgets.QLineEdit(self.centralwidget)
        self.gene.setObjectName("gene")
        self.gridLayout.addWidget(self.gene, 1, 2, 1, 2)
        self.pc_ = QtWidgets.QLineEdit(self.centralwidget)
        self.pc_.setObjectName("pc_")
        self.gridLayout.addWidget(self.pc_, 2, 2, 1, 2)
        self.pm = QtWidgets.QLabel(self.centralwidget)
        self.pm.setObjectName("pm")
        self.gridLayout.addWidget(self.pm, 3, 0, 1, 2)
        self.pm_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.pm_2.setObjectName("pm_2")
        self.gridLayout.addWidget(self.pm_2, 3, 2, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 0, 1, 4)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 2, 1, 2)
        self.pc = QtWidgets.QLabel(self.centralwidget)
        self.pc.setObjectName("pc")
        self.gridLayout.addWidget(self.pc, 2, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.shixian)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.population_size.setText(_translate("MainWindow", "种群数量"))
        self.popu_size.setText(_translate("MainWindow", "2000"))
        self.generations.setText(_translate("MainWindow", "迭代次数"))
        self.gene.setText(_translate("MainWindow", "200"))
        self.pc_.setText(_translate("MainWindow", "0.6"))
        self.pm.setText(_translate("MainWindow", "变异概率"))
        self.pm_2.setText(_translate("MainWindow", "0.001"))
        self.pushButton.setText(_translate("MainWindow", "实现"))
        self.lineEdit.setText(_translate("MainWindow", "max"))
        self.pc.setText(_translate("MainWindow", "交配概率"))

    def shixian(self):
        popu_size=self.popu_size.text()
        gene= self.gene.text()
        pm=self.pm_2.text()
        pc=self.pc_.text()



# 主方法
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
    ui = Ui_MainWindow() # 创建PyQt5设计的窗体对象
    ui.setupUi(MainWindow) # 调用PyQt5窗体的方法对窗体对象进行初始化设置
    MainWindow.show() # 显示窗体
    sys.exit(app.exec_()) # 程序关闭时退出进程