# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mylogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import mymain
import main
from service import myservice
import base64
import sys
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 196)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 10, 321, 201))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.editName = QtWidgets.QLineEdit(self.widget)
        self.editName.setObjectName("editName")
        self.verticalLayout.addWidget(self.editName)
        self.editPwd = QtWidgets.QLineEdit(self.widget)
        self.editPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPwd.setObjectName("editPwd")
        self.verticalLayout.addWidget(self.editPwd)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnLogin = QtWidgets.QPushButton(self.widget)
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout_2.addWidget(self.btnLogin)
        self.btnExit = QtWidgets.QPushButton(self.widget)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_2.addWidget(self.btnExit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnExit.clicked.connect(MainWindow.close) # 关闭登录窗体
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # 输入密码后按回车键执行登录操作
        self.editPwd.editingFinished.connect(self.openMain)
        # 单击“登录”按钮执行登录操作
        self.btnLogin.clicked.connect(self.openMain)

    # 打开主窗体
    def openMain(self):
        myservice.userName = self.editName.text()  # 全局变量，记录用户名
        t=self.editPwd.text()
        # self.userPwd=base64.b64encode(t.encode()) #base64进行加密并记录下来
        self.userPwd = self.editPwd.text()  # 记录用户密码


        '''简易加密过程'''
        self.userPwd=self.userPwd+'1'




        if myservice.userName != "" and self.userPwd != "":  # 判断用户名和密码不为空
            # 根据用户名和密码查询数据
            result = myservice.query2("select * from tb_pwd where user = '{}' and password = '{}'".format(myservice.userName,self.userPwd))
            cl=myservice.query2("select Uclass from tb_user where Uuser = '{}'".format(myservice.userName))
            # print(cl)
            myservice.Uclass=cl[0][0]
            # print(result)
            if len(result) > 0:  # 如果查询结果大于0，说明存在该用户，可以登录
                # myservice.Uclass=result #将查询到的用户类型记录下来
                self.m = mymain.Ui_MainWindow()  # 创建主窗体对象
                self.m.show()  # 显示主窗体
                MainWindow.hide()  # 隐藏当前的登录窗体
            else:
                self.editName.setText("")  # 清空用户名文本
                self.editPwd.setText("")  # 清空密码文本框
                QMessageBox.warning(None, '警告', '请输入正确的用户名和密码！', QMessageBox.Ok)
        else:
            QMessageBox.warning(None, '警告', '请输入用户名和密码！', QMessageBox.Ok)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "系统登录"))
        self.label_2.setText(_translate("MainWindow", "用户名："))
        self.label_3.setText(_translate("MainWindow", "密  码："))
        self.btnLogin.setText(_translate("MainWindow", "登  录"))
        self.btnExit.setText(_translate("MainWindow", "退  出"))
import img_rc



if __name__ == '__main__':

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
    ui = Ui_MainWindow() # 创建PyQt5设计的窗体对象
    ui.setupUi(MainWindow) # 调用PyQt5窗体的方法对窗体对象进行初始化设置
    MainWindow.show() # 显示窗体
    sys.exit(app.exec_()) # 程序关闭时退出进程

    # myservice.userName='1234@local'
    # userPwd=456
    # result = myservice.query2(
    #     "select * from tb_pwd where user = '{}' and password = '{}';".format(myservice.userName, userPwd))
    # print(result)